# pandas의 df.rename()을 이용하기

In [4]:
import pandas as pd

In [5]:
df_raw = pd.DataFrame({'var1' : [1,2,1],
                       'var2' : [2,3,2]})
df_raw

   var1  var2
0     1     2
1     2     3
2     1     2

# 2. 데이터 프레임 복사본 만들기

변수명을 바꾸기 전에 원본을 보존하기 위해 데이터 프레임 복사본을 만든다. 새 변수명 df_new에 df_raw.copy()를 할당하는 형태로 코드를 작성하면 된다.

In [6]:
df_new = df_raw.copy() # 복사본 만들기
df_new                 # 출력

   var1  var2
0     1     2
1     2     3
2     1     2

# 3. 변수명 바꾸기

복사본을 만들었으면 df.rename()을 이용해서 변수명을 바꾸는데, df_new.rename()에 columns파라미터를 추가한 다음 {'기존 변수명' : '새 변수명'}을 입력하면 된다.

In [7]:
df_new = df_new.rename(columns = {'var2' : 'v2'}) #var2를 v2로 수정
df_new

   var1  v2
0     1   2
1     2   3
2     1   2

In [8]:
df_raw

   var1  var2
0     1     2
1     2     3
2     1     2

In [9]:
df_new

   var1  v2
0     1   2
1     2   3
2     1   2